[client]
showSidebarNavigation = true

[server]
headless = true
port = 8501
enableCORS = false

[theme]
primaryColor = "#2563EB"
backgroundColor = "#0B1220"
secondaryBackgroundColor = "#0F1A2B"
textColor = "#E5E7EB"
font = "Inter"
